# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    defaults:
      run:
        working-directory: 'editor' # Here the path to the folder where package-lock.json is located.

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive' # If you have submodules, set this to true
      name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "**/package-lock.json"

    - run: |
        npm i
        npm install --global @vscode/vsce
        mkdir dist
        vsce package --out "dist/"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: |
          ./editor/dist
