# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: package_extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    defaults:
      run:
        working-directory: 'editor' # Here the path to the folder where package-lock.json is located.

    steps:
    - uses: actions/checkout@v3
      name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: "**/package-lock.json"

    - run: |
        npm i
        npm install --global vsce
        mkdir dist
        vsce package --out "dist/"


  create_artifact:
    name: create_artifact
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
    - uses: actions/upload-artifact@v3
      with:
          name: package
          path: |
            ./editor/dist

  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Publish Extension (Code Marketplace, release)
        working-directory: editor
        run: npx vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }} --packagePath ./dist/*.vsix
