# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish

on:
  workflow_call:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Publish Extension (Code Marketplace, release)
        working-directory: editor
        run: |
          npm i
          npm install --global @vscode/vsce
          mkdir dist
          npx vsce package --out "dist/"
          npx vsce publish --pat ${{ secrets.VS_MARKETPLACE_TOKEN }} --packagePath ./dist/$(find . -iname *.vsix)
